from . import CabinetController
from . import ChangeResultStateController
from . import ChoseStudentStateController
from . import ChoseSubmitStateController
from . import ChoseTaskStateController
from . import CommandController
from . import HelpMenuStateController
from . import SendMessageStateController
from . import StudentMenuStateController
from . import TaskMenuStateController
from . import TeacherMenuStateController
from . import WaitAuthStateController
