PATH_TO_SUBMIT = "/data/submit.sqlite"
PATH_TO_USER = "/data/user.sqlite"
PATH_TO_TASKS = "/tasks"
GRADING_SERVICE_URL = "http://testsys:8080/"
PATH_TO_LOGS = "/logs/bot.txt"
PATH_TO_KEY = "/secrets/bot_key.txt"
